# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 720e22e0afee5a8f1974599a9d8c5bdee538fecad617fcb9003015b18862607838a88ac3eb481f59aa8108db52170597f290928ba9af80ced70e9cfc4ef58f6f
  secret_api: G2sP6oZotxW1X20WgtBmMpkng2AFXX3YW22daY-5Cfv0aFCBqCjqn_G4Pt0vJDEtgXux2aaiEmBIU9gCSBbYr-WZT13JdbSHTRXghBMzq8OV51Trh0gpcRPXhMUM0mQ-6_YY1TMnBccMStDvbW2rUJe-KkTPEEBAV_EcPd9wRjScViNk7vdjMgvBoo3tFvXitq5R2KVQoNFDLQLtUKkaEN-fmweLle89tlaYXqiH5ysJsPgGH0Ta8M6Ubo2kLJeLaj4bFZ7gDSBab35LOyx3pUYnEfKf3v_WdE1f61yaJMa-m6_yHCapNHScqMn3E_UdV4mJwQ3Lv9OM9Mag0uCYNYGtq-A
  API_KEY: 9Sx4B3FmnMRRLEA7OLzoV9Hlp43H8xA2C-itm-4T0TuzJVKC4M0PHCwKJf9d-YhKBEbQcxQXxFoNVMz6s5vJKbyHyL8RMJqP5bn3-rrkOCptCJ1bYzm_RTCUy-Zf2G3RyE1b3qGyDe1m_BdCSWodPjDB-tM6dzUpNSUojyPNkxlab7ZEr1a14YzsJfxwJOmY1pNx1iVrdFSEHj4_rsKgfrucVde0uDIDNBesljZmq1aC2ZpiPXxq5qCbUbLeWpfpDR4bd8BH6qZ4nnlV8BA_kglqgt0vKcR7dB4aSk951SC2v8GDi_Bu1RP-a4Bl_WulAy0nDxqTeaGqr143PuXnL-qZMEA

test:
  secret_key_base: c93ef5680547d1b015893d5b5e7384bf3558b026f1eeecc4d1b01ddd73a76af92168b1e7574fa6479795d7075e45404efbc09d92e07eb7acadc9a626ea0eb7b4
  secret_api: G2sP6oZotxW1X20WgtBmMpkng2AFXX3YW22daY-5Cfv0aFCBqCjqn_G4Pt0vJDEtgXux2aaiEmBIU9gCSBbYr-WZT13JdbSHTRXghBMzq8OV51Trh0gpcRPXhMUM0mQ-6_YY1TMnBccMStDvbW2rUJe-KkTPEEBAV_EcPd9wRjScViNk7vdjMgvBoo3tFvXitq5R2KVQoNFDLQLtUKkaEN-fmweLle89tlaYXqiH5ysJsPgGH0Ta8M6Ubo2kLJeLaj4bFZ7gDSBab35LOyx3pUYnEfKf3v_WdE1f61yaJMa-m6_yHCapNHScqMn3E_UdV4mJwQ3Lv9OM9Mag0uCYNYGtq-A


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_api: <%= ENV["SECRET_API"] %>
